steps:
- script: 'python -m pip install --upgrade pip setuptools wheel --upgrade-strategy=eager && python -m pip install -e . --upgrade'
  displayName: Upgrade Pip & Install Pipenv
  env:
    PYTHONWARNINGS: 'ignore:DEPRECATION'
