parameters:
  python_version: ''

steps:
- script: |
    # Fix Git SSL errors
    echo "Using pipenv python version: $(PIPENV_DEFAULT_PYTHON_VERSION)"
    git submodule sync && git submodule update --init --recursive
    pipenv run pytest -n 4 --junitxml=test-results.xml
  displayName: Run integration tests
  env:
    PYTHONWARNINGS: ignore:DEPRECATION
    PIPENV_NOSPIN: '1'
    PIPENV_DEFAULT_PYTHON_VERSION: ${{ parameters.python_version }}
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=accept-new -o CheckHostIP=no
